allnames = ['Paul Dragos Aligica',
 'Neera Badhwar',
 'David Beckworth',
 'Charles Blahous',
 'Peter J. Boettke',
 'Donald J. Boudreaux',
 'James Broughel',
 'Bryan Caplan',
 'Tyler Cowen',
 'Christopher Coyne',
 'Rachel Coyne',
 'Veronique de Rugy',
 'Jerry Ellig',
 'Michael Farren',
 'Jason J. Fichtner',
 'Jack Goldstone',
 'Robert Graboyes',
 'Daniel Griswold',
 'Tim Groseclose',
 'Stefanie Haeffele',
 'Omar Ahmad Al-Ubaydli',
 'Dustin Chambers',
 'Emily Chamlee-Wright',
 'Seth J. Chandler',
 'Antony Davies',
 'John R. Graham',
 'Abigail Hall',
 'Steven Horwitz',
 'Arnold Kling',
 'Brian Kogelmann',
 'Robert Krol',
 'Chandran Kukathas',
 'Paul Lewis',
 'Deirdre McCloskey',
 'Christina McRorie',
 'Thomas W. Miller, Jr.',
 'Adam Millsap',
 'Johanna Mollerstrom',
 'Liya Palagashvili',
 'David M. Primo',
 'Bobbi Herzberg',
 'Arielle John',
 'Noel D. Johnson',
 'Garett Jones',
 'Daniel Klein',
 'Brian Knight',
 'Christopher Koopman',
 'Mark Koyama',
 'Peter Leeson',
 'Jayme Lemke',
 'Kevin McCabe',
 'Christine McDaniel',
 'Patrick McLaughlin',
 'Maurice P. McTigue',
 'Stephen Matteo Miller',
 'Matthew D. Mitchell',
 'Eileen Norcross',
 'John Nye',
 'Hester Peirce',
 'Hilton Root',
 'David Schmidtz',
 'George Selgin',
 'Vernon Smith',
 'Jason Sorens',
 'Nona Martin Storr',
 'Daniel Sutter',
 'Chad Van Schoelandt',
 'Richard Williams',
 'Walter Williams',
 'Claudia Williamson',
 'Bruce Yandle',
 'Brent Skorup',
 'Solomon Stein',
 'Virgil Storr',
 'Thomas Stratmann',
 'Scott Sumner',
 'Alexander Tabarrok',
 'Adam Thierer',
 'J. W. Verret',
 'Richard Wagner',
 'Lawrence H. White',
 'Todd Zywicki']

first_names = [i.split()[0] for i in allnames]
print(first_names)

